name: validate_push
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker install
        run: |
          docker build -t my-app .
          docker run -d -p 8080:8080 my-app
      - name: test
        run: |
          curl -f curl http://localhost:8080/users || exit 1 
          echo "Application is running successfully!"