name: validate_push
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker install
        run: |
          docker build -t my-app .

      - name: Scan with Trivy
        uses: aquasecurity/trivy-action@v0.20.0
        with:
          image-ref: my-app
          format: 'table'
          exit-code: '1'
          severity-threshold: 'HIGH'